apiVersion: v1
kind: Service
metadata:
  name: order-gateway
spec:
  ports:
    - name: local-subscription-port
      port: 8000
      targetPort: 8000
      protocol: UDP
    - name: cluster-egress-port
      port: 8020
      targetPort: 8020
      protocol: UDP
    - name: cluster-ingress-port
      port: 9010
      targetPort: 9010
      protocol: UDP
  selector:
    app: order-gateway
  sessionAffinity: None