apiVersion: v1
kind: Service
metadata:
  name: order-cluster2
spec:
  selector:
    app: order-cluster2
  ports:
    - name: egress-port
      port: 8000
      targetPort: 8000
      protocol: UDP
    - name: archive-control-port
      port: 9001
      targetPort: 9001
      protocol: UDP
    - name: client-facing-port
      port: 9002
      targetPort: 9002
      protocol: UDP
    - name: member-facing-port
      port: 9003
      targetPort: 9003
      protocol: UDP
    - name: log-port
      port: 9004
      targetPort: 9004
      protocol: UDP
    - name: transfer-port
      port: 9005
      targetPort: 9005
      protocol: UDP
    - name: log-control-port
      port: 9006
      targetPort: 9006
      protocol: UDP
    - name: ingress-port
      port: 9010
      targetPort: 9010
      protocol: UDP
    - name: replication-archive-port
      port: 9021
      targetPort: 9021
      protocol: UDP
    - name: replication-consensus-port
      port: 9022
      targetPort: 9022
      protocol: UDP
  sessionAffinity: None